# Generated by Django 5.0.1 on 2024-01-10 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_pokemonentity_defence_pokemonentity_health_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='appeared_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 20, 13, 39, 437008, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='disappeared_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 20, 13, 39, 441028, tzinfo=datetime.timezone.utc)),
        ),
    ]
